jobs:
  - name: jobA
    plan:
      - get: res-1
        passed: [jobB]

  - name: jobB
    plan:
      - get: res-1
        passed: [jobA]
      - get: res-2

resources:
  - name: res-1
    type: time
    source: {interval: 2m}

  - name: res-2
    type: time
    source: {interval: 2m}
