jobs:
  - name: jobA0
    plan:
      - get: res-1

  - name: jobA
    plan:
      - get: res-1
        passed: [jobC]

  - name: jobB
    plan:
      - get: res-1
        passed: [jobA]

  - name: jobC
    plan:
      - get: res-1
        passed: [jobB]

  - name: jobD
    plan:
      - get: res-1
        passed: [jobC]
      - get: res-2

resources:
  - name: res-1
    type: time
    source: {interval: 2m}

  - name: res-2
    type: time
    source: {interval: 2m}
