jobs:
  - name: jobA
    plan:
      - get: res-1
        passed: [jobC]

  - name: jobB
    plan:
      - get: res-1
        passed: [jobA]

  - name: jobC
    plan:
      - get: res-1
        passed: [jobB]

resources:
  - name: res-1
    type: time
    source: {interval: 2m}
